# Generated by Django 3.2.25 on 2025-11-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
    ]
